-- Generated by hyprconf2lua v1.3.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local primary = "rgb(ffffff)"
local surface = "rgb(131313)"
local secondary = "rgb(c6c6c6)"
local error = "rgb(ffb4ab)"

hl.config({
    general = {
        col = {
            active_border = primary,
            inactive_border = surface,
        },
    },
    group = {
        groupbar = {
            col = {
                active = secondary,
                inactive = surface,
                locked_active = error,
                locked_inactive = surface,
            },
        },
        col = {
            border_active = secondary,
            border_inactive = surface,
            border_locked_active = error,
            border_locked_inactive = surface,
        },
    },
})
