# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
#exec-once = nm-applet &
#exec-once = elephant & disown
#exec-once = wl-paste --watch cliphist store
#exec-once = hyprctl setcursor Polarnight-cursors 24
# exec-once = espanso start
#exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
#exec-once = hyprpm reload
#exec-once = sleep 1 && qs -c noctalia-shell --no-duplicate

exec-once = uwsm app -- nm-applet
#exec-once = rm -f /run/user/1000/elephant/elephant.sock && uwsm app -- elephant
exec-once = uwsm app -- wl-paste --watch cliphist store
exec-once = uwsm app -- hyprctl setcursor Polarnight-cursors 24
#exec-once = uwsm app -- espanso start
exec-once = uwsm app -- qs -c noctalia-shell --no-duplicate
exec-once = uwsm app -- hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
exec-once = uwsm app -- hyprpm reload
exec-once = uwsm app -- /usr/bin/protonvpn-app