# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = hyprlock
exec-once = waybar
exec-once = wl-paste --watch cliphist store
exec-once = hyprctl setcursor Polarnight-cursors 24
exec-once = nwg-dock-hyprland -i 32 -mb 6 -d -lp start -hd 0 -hl top -iw "special,scratchpad"

# load all the plugins you installed (hyprpm)
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
exec-once = hyprpm reload
exec-once = hyprpaper

# Dev Utilities
exec-once = ~/apps/jetbrains-toolbox-2.6.3.43718/bin/jetbrains-toolbox
exec = hyprshade auto