# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = nm-applet &
exec-once = elephant & disown
exec-once = qs -c noctalia-shell --no-duplicate
exec-once = wl-paste --watch cliphist store
exec-once = hyprctl setcursor Polarnight-cursors 24
exec-once = espanso start

# load all the plugins installed (hyprpm)
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
exec-once = hyprpm reload
