###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal = alacritty 
$fileManager = dolphin # nemo
$menu = walker # wofi --show drun
$browser = zen-browser # firefox

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_THEME, Polarnight-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = NIXOS_OZONE_WL,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

#####################
### IMPORT CONFIG ###
#####################
source = ~/.config/hypr/auto-start.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybind.conf
source = ~/.config/hypr/window.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/permission.conf
source = /home/lynhe/.config/hypr/noctalia/noctalia-colors.conf