###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal = ghostty #alacritty 
$fileManager = dolphin # nemo
$menu = qs -c noctalia-shell ipc call launcher toggle # walker
$browser = brave # zen-browser
$notepad = leafpad

#####################
### IMPORT CONFIG ###
#####################
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/auto-start.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybind.conf
source = ~/.config/hypr/window.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/permission.conf
source = /home/lynhe/.config/hypr/noctalia/noctalia-colors.conf
