monitor=DP-3,1920x1080@180.00,0x0,1
monitor=HDMI-A-1,1920x1080@74.97,1920x0,1

exec-once = hyprctl dispatch moveworkspacetomonitor 1 DP-3
exec-once = hyprctl dispatch moveworkspacetomonitor 2 HDMI-A-1
exec-once = ~/.config/hypr/script/fix-workspace.sh

workspace = 1,monitor:DP‑3
workspace = 2,monitor:HDMI‑A‑1
workspace = 3,monitor:DP‑3
workspace = 4,monitor:HDMI‑A‑1