plugin {
    hyprbars {
        # example config
        bar_height = 20

        bar_text_font = "JetBrainsMono Nerd Font"
        bar_text_size = 10

        bar_button_padding = 5

        bar_buttons_alignment = left
        bar_precedence_over_border = true
        bar_part_of_window = true

        inactive_button_color = rgba(46, 49, 51, 0)
        icon_on_hover = true
        # hyprbars-button = color, size, on-click, fg colors
        hyprbars-button = rgb(eeee11), 12, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(ff4040), 12, 󰖭, hyprctl dispatch killactive

        # cmd to run on double click of the bar
        on_double_click = hyprctl dispatch fullscreen 1
    }
    hyprtrails {
        color = rgba(e0e0e0dd)
    }
}
