# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Add Picture-in-Picture window to floating mode
windowrulev2 = float, title:.*Picture-in-Picture.*
windowrulev2 = float, title:.*PIP.*

windowrulev2 = float, class:^(MuPDF)$
windowrulev2 = float, class:^(kitty)$
windowrulev2 = float, class:^(Alacritty)$
windowrulev2 = float, class:^(org.gnome.gedit)$
windowrulev2 = float, class:^(org.kde.ark)$
windowrulev2 = float, class:^(org.kde.kcalc)$

# Fix JetBrains IDE
windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1
# center the pops excepting context menu
windowrulev2 = move 30% 30%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1
windowrulev2 = size 40% 40%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1

windowrulev2=noblur,class:^(thunar)$,title:^()$
