# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Disable blur to specific apps
windowrulev2= noblur, class:^(thunar)$,title:^()$

# Add Picture-in-Picture window to floating mode
windowrulev2 = float, title:.*Picture-in-Picture.*
windowrulev2 = float, title:.*PIP.*

# Start some window as floating by default
windowrulev2 = float, class:^(MuPDF)$
windowrulev2 = float, class:^(Alacritty)$
windowrulev2 = float, class:^(org.gnome.gedit)$
windowrulev2 = float, class:^(org.kde.ark)$
windowrulev2 = float, class:^(org.kde.kcalc)$

# Enable floating for the welcone Screen of IntelliJ IDEA and set in non floating for other window
windowrulev2 = float, class:^(jetbrains-idea)$,title:^(Welcome to IntelliJ IDEA)$
windowrulev2 = size 800 400, class:^(jetbrains-idea)$,title:^(Welcome to IntelliJ IDEA)$